#! /bin/bash -e

#####################
# Configuration     # 							     
#####################

### Sources
SRC_DIR="/var/tmp/embedux/download"
KERNEL_URL="http://www.kernel.org/pub/linux/kernel/v3.x"
KERNEL_FILE="linux-3.18.tar.gz"
KERNEL_SHA="sha256sums.asc"

### Patches
GPATCH_DIR="gentoo-patches"
GPATCH_URL="http://dev.gentoo.org/~mpagano/genpatches/tarballs"
GPATCH_BASE_FILE="genpatches-3.18-2.base.tar.xz"
GPATCH_EXTRAS_FILE="genpatches-3.18-2.extras.tar.xz"
GPATCH_EXPERIMENTAL_FILE=" genpatches-3.18-2.experimental.tar.xz"

#####################
# Script            #
#####################

### Prepare folder
mkdir -p ${SRC_DIR}

### Kernel sources and patches

echo "Downloading ${KERNEL_SHA} from ${KERNEL_URL}"
wget -N ${KERNEL_URL}/${KERNEL_SHA} -P ${SRC_DIR}
echo "Downloading ${KERNEL_FILE} from ${KERNEL_URL}"
wget -N ${KERNEL_URL}/${KERNEL_FILE} -P ${SRC_DIR}

echo "Checking sha265 hash on ${KERNEL_FILE}"
if [[ -z $(grep `shasum -a 256 ${SRC_DIR}/${KERNEL_FILE}` ${SRC_DIR}/${KERNEL_SHA}) ]]
  then exit
fi

echo "Extracting ${KERNEL_FILE}"
tar -xf ${SRC_DIR}/${KERNEL_FILE} --strip 1

### Gentoo patchset
mkdir ${GPATCH_DIR}

echo "Downloading ${GPATCH_BASE_FILE} from ${KERNEL_URL}"
wget -N ${GPATCH_URL}/${GPATCH_BASE_FILE} -P ${SRC_DIR}

echo "Extracting ${GPATCH_BASE_FILE}"
tar -xf ${SRC_DIR}/${GPATCH_BASE_FILE} -C ${GPATCH_DIR}

echo "Downloading ${GPATCH_EXTRAS_FILE} from ${KERNEL_URL}"
wget -N ${GPATCH_URL}/${GPATCH_EXTRAS_FILE} -P ${SRC_DIR}

echo "Extracting ${GPATCH_EXTRAS_FILE}"
tar -xf ${SRC_DIR}/${GPATCH_EXTRAS_FILE} -C ${GPATCH_DIR}

echo "Downloading ${GPATCH_EXPERIMENTAL_FILE} from ${KERNEL_URL}"
wget -N ${GPATCH_URL}/${GPATCH_EXPERIMENTAL_FILE} -P ${SRC_DIR}
echo "Extracting ${GPATCH_EXPERIMENTAL_FILE}"
tar -xf ${SRC_DIR}/${GPATCH_EXPERIMENTAL_FILE} -C ${GPATCH_DIR}

### Apply gentoo patchset
echo "Applying gentoo patches"
for patch in $(ls ${GPATCH_DIR}/*.patch 2>/dev/null) 
	do patch -t -p1 < $patch
done
